baseurl = "https://cop.thegauthams.com"
DefaultContentLanguage = "en"
title = "Constructs of Python"
# Using theme as git submodule
theme = "beautifulhugo"
# Or when using theme as hugo module
# theme = "github.com/halogenica/beautifulhugo"
pygmentsStyle = "trac"
pygmentsUseClasses = true
pygmentsCodeFences = true
pygmentsCodefencesGuessSyntax = true
#pygmentsUseClassic = true
#pygmentOptions = "linenos=inline"

[Services]
  [Services.Disqus]
    # Shortname = "XXX"
  [Services.googleAnalytics]
    # id = "G-FJ0KFYP31Z"

[Params]
#  homeTitle = "Beautiful Hugo Theme" # Set a different text for the header on the home page
  subtitle = "Live Instructor Led Programs to learn: Python, RDBMS & Data Engineering."
  mainSections = ["post","posts"]
  logo = "img/python.png" # Expecting square dimensions
  # favicon = "img/favicon.ico"
  favicon = "img/python.img"
  dateFormat = "January 2, 2006"
  commit = false
  rss = true
  comments = true
  readingTime = true
  wordCount = true
  useHLJS = true
  socialShare = true
  delayDisqus = true
  showRelatedPosts = true
  pygmentsCodeFences = true
  pygmentsUseClasses = true
#  cusdisID = "XXX" # Get your App id from cusdis.com
#  hideAuthor = true
#  gcse = "012345678901234567890:abcdefghijk" # Get your code from google.com/cse. Make sure to go to "Look and Feel" and change Layout to "Full Width" and Theme to "Classic"
#  disclaimerText = "The opinions expressed herein are my own personal opinions and do not represent my employer’s view in any way."

#[[Params.bigimg]]
#  src = "img/triangle.jpg"
#  desc = "Triangle"
#[[Params.bigimg]]
#  src = "img/sphere.jpg"
#  desc = "Sphere"
#  # position: see values of CSS background-position.
#  position = "center top"
#[[Params.bigimg]]
#  src = "img/hexagon.jpg"
#  desc = "Hexagon"

[Params.author]
  # Set only your "username" for default hosts and full URLs otherwise (e.g., "https://MyGitLab.org/username")
  name = "Gautham Kolluru"
  website = "thegauthams.com"
  email = "gautham.kolluru@gmail.com"
  # facebook = "username"
  github = "gauthamkolluru"
  # gitlab = "username"
  # bitbucket = "username"
  # twitter = "username"
  reddit = "gauthamkolluru"
  linkedin = "gautamkolluru"
  # xing = "username"
  stackoverflow = "users/7315848/gautham-kolluru"
  # snapchat = "username"
  # instagram = "username"
  # youtube = "user/username" # or channel/channelname
  youtube = "@gauthamkolluru"
  # soundcloud = "username"
  # spotify = "username"
  # bandcamp = "username"
  # itchio = "username"
  # vk = "username"
  # paypal = "username"
  # telegram = "username"
  # 500px = "username"
  # codepen = "username"
  # mastodon = "url"
  # kaggle = "username"
  # weibo = "username"
  # slack = "username"
  medium = "gautham.kolluru"
  discord = "gk7587"
  # strava = "userid"
  # lastfm = "username"

[[menu.main]]
    identifier = "programs"
    name = "Programs"
    # url = ""
    weight = 1

[[menu.main]]
    parent = "programs"
    name = "Python Bootcamp"
    url= "page/python_bootcamp/"
    weight = 1

[[menu.main]]
    parent = "programs"
    name = "Data Engineering"
    url= "page/data_engineering/"
    weight = 2

[[menu.main]]
    parent = "programs"
    name = "RDBMS in 1 Day"
    url= "page/rdbms/"
    weight = 3

[[menu.main]]
    name = "About"
    url = "page/about/"
    weight = 3